### ISSUE TITLE
建议增加世纪互联的支持

### ISSUE THREAD

**Issue by ifvv** [cugxuan/gonelist#1]
世纪互联和国际版就API请求地址不一样，官方文档：
https://docs.microsoft.com/zh-cn/previous-versions/office/office-365-api/api/o365-china-endpoints
这个commit是我做的一些修改，经测试可以正常运行
https://github.com/ifvv/gonelist/commit/a2b78511861dadbf4a7c76093a1cf92573e2e714

希望作者能够增加对世纪互联的支持，可以通过config.json自由切换国际版/世纪互联

**Comment by cugxuan** [comment]
在 [七色心](https://github.com/2218675712) 提供账号的帮助下，已经支持了世纪互联，不过没有默认的 clientid，等我申请开发者账号之后看看。暂时不会发新的 release，如果你现在需要一个临时的 release，可以进群，我发给你、

**Comment by cugxuan** [comment]
#
