### ISSUE TITLE
不能在线播放视频？

### ISSUE THREAD

**Issue by BrunuhVille** [cugxuan/gonelist#10]
onedrive和世纪互联均尝试绑定成功，可以正常下载，
但是在线播放一直是00:00。无法播放。视频是正常的mp4没有问题

**Comment by cugxuan** [comment]
您好，可以提供您的部署网址或者视频文件么。

**Comment by cugxuan** [comment]
经过排查，是程序 bug，`v0.3.2` 版本在第一次播放的时候不会加载对应视频。
现在解决方法，点某个视频的播放，然后点另一个视频的播放，就可以播放第二个视频、
