### ISSUE TITLE
[Feature] 下载链接加入前缀重定向

### ISSUE THREAD

**Issue by lhllhx** [cugxuan/gonelist#16]
请问服务器要反代加速该如何设置
是否可能利用cloudflaree进行加速

**Comment by lhllhx** [comment]
随便请求宝塔部署教程，我用反代的方式去处理不知道为什么会反代出来两个斜杠

**Comment by cugxuan** [comment]
加群有宝塔的文档，我还没空整理gonelist-doc，我写了nginx的反向代理方法，至于你说的这个反代加速我不太清楚，可以给点文档或者案例吗？

**Comment by lhllhx** [comment]
https://www.nbmao.com/archives/3916
利用服务器或者cloudflare反代加速下载连接

**Comment by cugxuan** [comment]
The new version already supports.
