### ISSUE TITLE
在vps上部署时，登录过后一直显示开始初始化，获取文件列表

### ISSUE THREAD

**Issue by Always67** [cugxuan/gonelist#20]
在这一步“将当前网址改成 http://yoursite:8000/auth?code=xxx 再回车等待文件加载后，会自动跳转你的网站 http://yoursite:8000”，改了之后，登录完长时间没有反应。ssh上显示：开始初始化，获取文件列表

**Comment by cugxuan** [comment]
> 在这一步“将当前网址改成 http://yoursite:8000/auth?code=xxx 再回车等待文件加载后，会自动跳转你的网站 [http://yoursite:8000”，改了之后，登录完长时间没有反应。ssh上显示：开始初始化，获取文件列表](http://yoursite:8000%E2%80%9D%EF%BC%8C%E6%94%B9%E4%BA%86%E4%B9%8B%E5%90%8E%EF%BC%8C%E7%99%BB%E5%BD%95%E5%AE%8C%E9%95%BF%E6%97%B6%E9%97%B4%E6%B2%A1%E6%9C%89%E5%8F%8D%E5%BA%94%E3%80%82ssh%E4%B8%8A%E6%98%BE%E7%A4%BA%EF%BC%9A%E5%BC%80%E5%A7%8B%E5%88%9D%E5%A7%8B%E5%8C%96%EF%BC%8C%E8%8E%B7%E5%8F%96%E6%96%87%E4%BB%B6%E5%88%97%E8%A1%A8)

可能是因为文件夹太多导致的，等几分钟看看、

**Comment by zhangguanzhang** [comment]
可以新建一个文件夹，选这个文件夹作为root文件夹，看下能否快速加载
